# Generated by Django 4.0.5 on 2022-07-18 22:01

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qpForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('visibility', models.PositiveSmallIntegerField(choices=[(0, 'Everyone'), (1, 'Creator Only'), (2, 'Administrators'), (3, 'Moderators'), (4, 'Validated Players'), (5, 'Players')], default=1, verbose_name='Visibility')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpForumChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['-last_message__created_at', '-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='qpForumMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('count_updates', models.PositiveSmallIntegerField(default=0, verbose_name='Updates')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='qpForumZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='forum.qpforum', verbose_name='Forum')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['forum', 'ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpForumTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Colour')),
                ('flexbasis', models.CharField(default='100%', max_length=9, verbose_name='Flex Basis')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='forum.qpforumzone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
                'ordering': ['zone', 'ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpForumSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Colour')),
                ('flexbasis', models.CharField(default='100%', max_length=9, verbose_name='Flex Basis')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Ordering')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='forum.qpforumterritory', verbose_name='Territory')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['territory', 'ordering', 'name'],
            },
        ),
    ]
