# Generated by Django 4.0.5 on 2022-07-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_qpplayer_banner'),
        ('forum', '0004_qpforumchapter_is_locked_alter_qpforum_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpForumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_at', models.DateTimeField(auto_now=True, verbose_name='Tracked')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='forum.qpforumchapter', verbose_name='Chapter')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='player.qpplayer', verbose_name='Player')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
                'ordering': ['-tracked_at'],
            },
        ),
    ]
