# Generated by Django 4.0.5 on 2022-07-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_worlds', to='player.qpplayer', verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'World',
                'verbose_name_plural': 'Worlds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldEthnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethnicities', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicities',
                'ordering': ['name'],
            },
        ),
    ]
