# Generated by Django 4.0.5 on 2022-06-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qpWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'World',
                'verbose_name_plural': 'Worlds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['world', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldTerritoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Territory',
                'verbose_name_plural': 'Territories',
                'ordering': ['world', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'ordering': ['world', 'name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Race',
                'verbose_name_plural': 'Races',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationalities', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='qpWorldEthnicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethnicities', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicities',
                'ordering': ['name'],
            },
        ),
    ]
