# Generated by Django 4.0.5 on 2022-07-12 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpworldsector',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='qpworldterritoty',
            name='slug',
        ),
        migrations.AddField(
            model_name='qpworldsector',
            name='flexbasis',
            field=models.CharField(default='100%', max_length=5, verbose_name='Flex Basis'),
        ),
        migrations.AddField(
            model_name='qpworldterritoty',
            name='flexbasis',
            field=models.CharField(default='100%', max_length=5, verbose_name='Flex Basis'),
        ),
        migrations.AlterField(
            model_name='qpworldsector',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='world.qpworldterritoty', verbose_name='Territory'),
        ),
        migrations.AlterField(
            model_name='qpworldterritoty',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='world.qpworldzone', verbose_name='Zone'),
        ),
    ]
