# Generated by Django 4.0.5 on 2022-07-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworld',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='admin_worlds', to='player.qpplayer', verbose_name='Administrators'),
        ),
        migrations.AddField(
            model_name='qpworld',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='modo_worlds', to='player.qpplayer', verbose_name='Moderators'),
        ),
    ]
