# Generated by Django 4.0.5 on 2022-07-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_qpworldsector_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworld',
            name='stylesheet',
            field=models.TextField(default='', verbose_name='Custom Stylesheet'),
        ),
    ]
