# Generated by Django 4.0.5 on 2022-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_qpworld_administrators_qpworld_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworld',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='qpworld',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Everyone'), (1, 'Creator Only'), (2, 'Administrators'), (3, 'Moderators'), (4, 'Validated Players'), (5, 'Players')], default=1, verbose_name='Visibility'),
        ),
    ]
