# Generated by Django 4.0.5 on 2022-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_qpworld_is_active_qpworld_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpworld',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Everyone'), (1, 'Creator Only'), (2, 'Administrators'), (3, 'Moderators'), (4, 'Validated Players'), (5, 'Registered Players'), (6, 'Players')], default=1, verbose_name='Visibility'),
        ),
    ]
