# Generated by Django 4.0.5 on 2022-07-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_qpworld_stylesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpworldzone',
            name='slug',
        ),
        migrations.AddField(
            model_name='qpworldsector',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='qpworldterritoty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='qpworldzone',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
