# Generated by Django 4.0.5 on 2022-07-15 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_qpworldchapter_qpworldmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qpWorldTerritoty',
            new_name='qpWorldTerritory',
        ),
        migrations.AlterModelOptions(
            name='qpworldchapter',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterField(
            model_name='qpworld',
            name='stylesheet',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Custom Stylesheet'),
        ),
        migrations.AlterField(
            model_name='qpworldchapter',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='world.qpworldsector', verbose_name='Sector'),
        ),
    ]
