# Generated by Django 4.0.5 on 2022-07-25 01:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_qpworld_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpWorldStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('default_bg', colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=18, samples=None, verbose_name='Default Background Colour')),
                ('default_txt', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='Default Text Colour')),
                ('app_header_bg', colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='App Header Background Colour')),
                ('app_sidebar_bg', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=18, samples=None, verbose_name='App Sidebar Background Colour')),
                ('app_smallbar_bg', colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=18, samples=None, verbose_name='App Smallbar Background Colour')),
                ('stylesheet', models.TextField(default='', verbose_name='Custom Stylesheet')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Style',
                'verbose_name_plural': 'Styles',
                'ordering': ['name'],
            },
        ),
    ]
