# Generated by Django 4.0.5 on 2022-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0006_rename_qpworldterritoty_qpworldterritory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpworldmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='qpworldmessage',
            name='count_updates',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Updates'),
        ),
        migrations.AlterField(
            model_name='qpworldsector',
            name='flexbasis',
            field=models.CharField(default='100%', max_length=9, verbose_name='Flex Basis'),
        ),
        migrations.AlterField(
            model_name='qpworldterritory',
            name='flexbasis',
            field=models.CharField(default='100%', max_length=9, verbose_name='Flex Basis'),
        ),
    ]
