# Generated by Django 4.0.5 on 2022-07-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_alter_qpworldmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpworldchapter',
            name='title',
            field=models.CharField(max_length=90, verbose_name='Title'),
        ),
    ]
