# Generated by Django 4.0.5 on 2022-07-25 11:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0007_rename_default_bg_qpworldstyle_app_body_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='app_header_txt',
            field=colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=18, samples=None, verbose_name='App Header Text Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='app_header_txt_hov',
            field=colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=18, samples=None, verbose_name='App Header Text Hover Colour'),
        ),
        migrations.AlterField(
            model_name='qpworldstyle',
            name='app_body_bg',
            field=colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=18, samples=None, verbose_name='App Background Colour'),
        ),
        migrations.AlterField(
            model_name='qpworldstyle',
            name='app_body_txt',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='App Text Colour'),
        ),
    ]
