# Generated by Django 4.0.5 on 2022-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_qpworld_administrators_qpworld_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpworldterritory',
            options={'ordering': ['zone', 'ordering', 'name'], 'verbose_name': 'Territory', 'verbose_name_plural': 'Territories'},
        ),
        migrations.AlterModelOptions(
            name='qpworldzone',
            options={'ordering': ['world', 'ordering', 'name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='qpworldterritory',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordering'),
        ),
        migrations.AddField(
            model_name='qpworldzone',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordering'),
        ),
    ]
