# Generated by Django 4.0.5 on 2022-07-26 22:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_qpworldstyle_app_sidebar_txt_qpworldstyle_default_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='app_sidebar_accent',
            field=colorfield.fields.ColorField(default='#937c0c', image_field=None, max_length=18, samples=None, verbose_name='App Sidebar Accent Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='app_smallbar_accent',
            field=colorfield.fields.ColorField(default='#937c0c', image_field=None, max_length=18, samples=None, verbose_name='App Smallbar Accent Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='app_smallbar_txt',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='App Smallbar Text Colour'),
        ),
        migrations.AlterField(
            model_name='qpworldstyle',
            name='app_sidebar_txt',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='App Sidebar Text Colour'),
        ),
    ]
