# Generated by Django 4.0.5 on 2022-07-26 23:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_qpworldstyle_app_sidebar_accent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='default_txt',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='Default Text Colour'),
        ),
    ]
