# Generated by Django 4.0.5 on 2022-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0010_alter_qpworldterritory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpworldsector',
            options={'ordering': ['territory', 'ordering', 'name'], 'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AddField(
            model_name='qpworldsector',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordering'),
        ),
    ]
