# Generated by Django 4.0.5 on 2022-07-26 23:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_qpworldstyle_default_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='default_disabled_bg',
            field=colorfield.fields.ColorField(default='#c9cfd1', image_field=None, max_length=18, samples=None, verbose_name='Default Disabled Background Colour'),
        ),
    ]
