# Generated by Django 4.0.5 on 2022-07-17 08:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0011_alter_qpworldsector_options_qpworldsector_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldsector',
            name='colour',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Colour'),
        ),
        migrations.AddField(
            model_name='qpworldterritory',
            name='colour',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None, verbose_name='Colour'),
        ),
    ]
