# Generated by Django 4.0.5 on 2022-07-26 23:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_qpworldstyle_default_disabled_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='default_disabled_txt',
            field=colorfield.fields.ColorField(default='#6e7f86', image_field=None, max_length=18, samples=None, verbose_name='Default Disabled Text Colour'),
        ),
    ]
