# Generated by Django 4.0.5 on 2022-07-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0012_qpworldsector_colour_qpworldterritory_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldchapter',
            name='last_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lastmessage_chapter', to='world.qpworldmessage', verbose_name='Last Message'),
        ),
    ]
