# Generated by Django 4.0.5 on 2022-07-26 23:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_qpworldstyle_default_disabled_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='default_accented_bg',
            field=colorfield.fields.ColorField(default='#435259', image_field=None, max_length=18, samples=None, verbose_name='Default Accented Background Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='default_accented_txt',
            field=colorfield.fields.ColorField(default='#dbe0e2', image_field=None, max_length=18, samples=None, verbose_name='Default Accented Text Colour'),
        ),
    ]
