# Generated by Django 4.0.5 on 2022-07-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_qpworldchapter_last_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qpworldchapter',
            options={'ordering': ['-last_message__created_at', '-updated_at', '-created_at'], 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
    ]
