# Generated by Django 4.0.5 on 2022-07-26 23:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_qpworldstyle_default_accented_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='form_bg',
            field=colorfield.fields.ColorField(default='#d2d7d9', image_field=None, max_length=18, samples=None, verbose_name='Form Background Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='form_placeholder',
            field=colorfield.fields.ColorField(default='#899295', image_field=None, max_length=18, samples=None, verbose_name='Form Placeholder Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='form_txt',
            field=colorfield.fields.ColorField(default='#7a8489', image_field=None, max_length=18, samples=None, verbose_name='Form Text Colour'),
        ),
    ]
