# Generated by Django 4.0.5 on 2022-07-30 16:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0015_qpworldstyle_form_bg_qpworldstyle_form_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='header',
            field=models.CharField(choices=[('default', 'Default'), ('simple', 'Simple')], default='default', max_length=12, verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='qpworldstyle',
            name='default_disabled_bg',
            field=colorfield.fields.ColorField(default='#b7c1c5', image_field=None, max_length=18, samples=None, verbose_name='Default Disabled Background Colour'),
        ),
        migrations.AlterField(
            model_name='qpworldstyle',
            name='default_txt',
            field=colorfield.fields.ColorField(default='#5a6b72', image_field=None, max_length=18, samples=None, verbose_name='Default Text Colour'),
        ),
        migrations.AlterField(
            model_name='qpworldstyle',
            name='form_placeholder',
            field=colorfield.fields.ColorField(default='#a5afb3', image_field=None, max_length=18, samples=None, verbose_name='Form Placeholder Colour'),
        ),
    ]
