# Generated by Django 4.0.5 on 2022-07-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0016_qpworldstyle_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworld',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='worlds/banners', verbose_name='Banner'),
        ),
    ]
