# Generated by Django 4.0.5 on 2022-07-31 15:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_qpworld_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpworldstyle',
            name='popper_bg',
            field=colorfield.fields.ColorField(default='#d2d7d9', image_field=None, max_length=18, samples=None, verbose_name='Popper Background Colour'),
        ),
        migrations.AddField(
            model_name='qpworldstyle',
            name='popper_txt',
            field=colorfield.fields.ColorField(default='#7a8489', image_field=None, max_length=18, samples=None, verbose_name='Popper Text Colour'),
        ),
    ]
