# Generated by Django 4.0.5 on 2022-06-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='qpPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=32, verbose_name='Playername')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('affinity', models.PositiveIntegerField(default=0, verbose_name='Affinity')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['-user__last_login'],
            },
        ),
        migrations.CreateModel(
            name='qpPlayerHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=2, verbose_name='Gender')),
                ('resistance_physical', models.PositiveSmallIntegerField(default=0, verbose_name='Physical Resistance')),
                ('resistance_mental', models.PositiveSmallIntegerField(default=0, verbose_name='Mental Resistance')),
                ('resistance_spiritual', models.PositiveSmallIntegerField(default=0, verbose_name='Spiritual Resistance')),
                ('attribute_strength', models.PositiveIntegerField(default=0, verbose_name='Strength')),
                ('attribute_constitution', models.PositiveIntegerField(default=0, verbose_name='Constitution')),
                ('attribute_dexterity', models.PositiveIntegerField(default=0, verbose_name='Dexterity')),
                ('attribute_perception', models.PositiveIntegerField(default=0, verbose_name='Perception')),
                ('attribute_intelligence', models.PositiveIntegerField(default=0, verbose_name='Intelligence')),
                ('attribute_composure', models.PositiveIntegerField(default=0, verbose_name='Composure')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heros', to='player.qpplayer', verbose_name='Player')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heros', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heros',
            },
        ),
        migrations.CreateModel(
            name='qpPlayerCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=2, verbose_name='Gender')),
                ('resistance_physical', models.PositiveSmallIntegerField(default=0, verbose_name='Physical Resistance')),
                ('resistance_mental', models.PositiveSmallIntegerField(default=0, verbose_name='Mental Resistance')),
                ('resistance_spiritual', models.PositiveSmallIntegerField(default=0, verbose_name='Spiritual Resistance')),
                ('attribute_strength', models.PositiveIntegerField(default=0, verbose_name='Strength')),
                ('attribute_constitution', models.PositiveIntegerField(default=0, verbose_name='Constitution')),
                ('attribute_dexterity', models.PositiveIntegerField(default=0, verbose_name='Dexterity')),
                ('attribute_perception', models.PositiveIntegerField(default=0, verbose_name='Perception')),
                ('attribute_intelligence', models.PositiveIntegerField(default=0, verbose_name='Intelligence')),
                ('attribute_composure', models.PositiveIntegerField(default=0, verbose_name='Composure')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='player.qpplayer', verbose_name='Player')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='world.qpworld', verbose_name='World')),
            ],
            options={
                'verbose_name': 'Companion',
                'verbose_name_plural': 'Companions',
            },
        ),
    ]
