# Generated by Django 4.0.5 on 2022-07-18 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('world', '0001_initial'),
        ('player', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayerhero',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heros', to='world.qpworld', verbose_name='World'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='player.qpplayer', verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='world.qpworld', verbose_name='World'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
