# Generated by Django 4.0.5 on 2022-07-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayercompanion',
            name='geo',
            field=models.TextField(blank=True, null=True, verbose_name='Geolocalisation'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='geo',
            field=models.TextField(blank=True, null=True, verbose_name='Geolocalisation'),
        ),
    ]
