# Generated by Django 4.0.5 on 2022-07-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_qpplayercompanion_geo_qpplayerhero_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='players/avatars', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='characters/avatars', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='characters/avatars', verbose_name='Avatar'),
        ),
    ]
