# Generated by Django 4.0.5 on 2022-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayercompanion',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
    ]
