# Generated by Django 4.0.5 on 2022-06-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_qpplayer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayer',
            name='attribute_composure',
            field=models.PositiveIntegerField(default=0, verbose_name='Composure'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='attribute_constitution',
            field=models.PositiveIntegerField(default=0, verbose_name='Constitution'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='attribute_dexterity',
            field=models.PositiveIntegerField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='attribute_intelligence',
            field=models.PositiveIntegerField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='attribute_perception',
            field=models.PositiveIntegerField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='attribute_strength',
            field=models.PositiveIntegerField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='resistance_mental',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mental Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='resistance_physical',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Physical Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayer',
            name='resistance_spiritual',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Spiritual Resistance'),
        ),
        migrations.AlterField(
            model_name='qpplayer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
