# Generated by Django 4.0.5 on 2022-06-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_qpplayer_attribute_composure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpplayer',
            name='attribute_composure',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='attribute_constitution',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='attribute_dexterity',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='attribute_intelligence',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='attribute_perception',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='attribute_strength',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='resistance_mental',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='resistance_physical',
        ),
        migrations.RemoveField(
            model_name='qpplayer',
            name='resistance_spiritual',
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='attribute_composure',
            field=models.PositiveIntegerField(default=0, verbose_name='Composure'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='attribute_constitution',
            field=models.PositiveIntegerField(default=0, verbose_name='Constitution'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='attribute_dexterity',
            field=models.PositiveIntegerField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='attribute_intelligence',
            field=models.PositiveIntegerField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='attribute_perception',
            field=models.PositiveIntegerField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='attribute_strength',
            field=models.PositiveIntegerField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='resistance_mental',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mental Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='resistance_physical',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Physical Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='resistance_spiritual',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Spiritual Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='attribute_composure',
            field=models.PositiveIntegerField(default=0, verbose_name='Composure'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='attribute_constitution',
            field=models.PositiveIntegerField(default=0, verbose_name='Constitution'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='attribute_dexterity',
            field=models.PositiveIntegerField(default=0, verbose_name='Dexterity'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='attribute_intelligence',
            field=models.PositiveIntegerField(default=0, verbose_name='Intelligence'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='attribute_perception',
            field=models.PositiveIntegerField(default=0, verbose_name='Perception'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='attribute_strength',
            field=models.PositiveIntegerField(default=0, verbose_name='Strength'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='resistance_mental',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Mental Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='resistance_physical',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Physical Resistance'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='resistance_spiritual',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Spiritual Resistance'),
        ),
    ]
