# Generated by Django 4.0.5 on 2022-06-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_qpplayer_attribute_composure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayer',
            name='affinity',
            field=models.PositiveIntegerField(default=0, verbose_name='Affinity'),
        ),
        migrations.AddField(
            model_name='qpplayercompanion',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=2, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='qpplayercompanion',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='player.qpplayer', verbose_name='Player'),
        ),
    ]
