# Generated by Django 4.0.5 on 2022-07-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_qpplayer_limits_create_heros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayer',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='players/banners', verbose_name='Banner'),
        ),
    ]
