# Generated by Django 4.0.5 on 2022-06-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('player', '0005_qpplayer_affinity_qpplayercompanion_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpplayercompanion',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companions', to='world.qpworld', verbose_name='World'),
        ),
        migrations.AddField(
            model_name='qpplayerhero',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heros', to='world.qpworld', verbose_name='World'),
        ),
    ]
